config/routes.rb
Hi::Application.routes.draw do

  devise_for :users

  resources :articles do
    resources :comments
  end
  resources :roles
  resources :parts
  resources :tags

  root :to => "articles#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if  !user.nil?
      can :read, Article
      can :create, Article
      can :update, Article do |article|
        (article.userInfo_id == user.id)
      end
      can :destroy, Article do |article|
        (article.userInfo_id == user.id )
      end
    else
      can :read, :all
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :userInfo,:class_name => "User", :foreign_key => "userInfo_id"
  belongs_to :part
  attr_accessible :body, :title,:tag_list,:tag,:part_id
  has_many :comments,:dependent => :destroy
  has_many :taggings 
  has_many :tags, :through =>:taggings
  self.per_page = 5
  
  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}

    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by_name(tag_name)
      tagging = self.taggings.new
      tagging.tag_id = tag.id
    end
  end
  def tag=(tag_id)
    tag = Tag.find(tag_id)
    tagging = self.taggings.new 
    tagging.tag_id = tag.id


  end
  def tag
    self.tags.collect do |tag|
            tag.name
                end.join(", ")
  end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :userInfo
  belongs_to :article
  attr_accessible :author_name, :body,:userInfo
end

app/models/part.rb
class Part < ActiveRecord::Base
  has_many :articles
  attr_accessible :desc, :name, :state
end

app/models/role.rb
=begin

=end


class Role < ActiveRecord::Base
  has_many :users
  attr_accessible :role_desc, :role_name, :state
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :articles,:through =>:taggings
  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :article
  belongs_to :tag
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :articles
  has_many :comments
  belongs_to :role
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :find_article, :only => [:show, :edit, :update, :destroy]

  def index
    if  !params[:tag_id].nil?
      @article_ids = Array.new
      Tagging.where(['tag_id = ?', params[:tag_id]]).each do |tagging|
        @article_ids << tagging.article_id
      end
      @articles = Article.where(["id in (?)", @article_ids]).order("created_at DESC").paginate(:page => params[:page])
    else
      @articles = Article.order("created_at DESC").paginate(:page => params[:page])
    end
    @tags = Tag.order("created_at DESC")

  end

  def new
    @article = Article.new
    @tags = Tag.all
  end

  def create
    @article = Article.new(params[:article])
    @article.userInfo_id = current_user.id
    @article.save
    redirect_to :action => :index , :notice => "Success"
  end

  def edit
  end

  def show
  end

  def update
    @article.update_attributes(params[:article])

    redirect_to :action => :show, :id => @article,  :flash => { :warning => "Update Success!" }
  end

  def destroy
    @article.destroy

    redirect_to :action => :index
  end

  protected

  def find_article
    @article = Article.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   before_filter :authenticate_user!
   skip_authorization_check

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_filter :find_part, :only => [ :show, :edit, :update, :destroy]
  layout "admin"
  def index
    @parts = Part.page(params[:page]).per(5)
  end

  def new
    @part = Part.new
  end

  def create
    @part = Part.new(params[:part])
    @part.save
    redirect_to :action => :index
  end

  def edit
  end

  def show
  end

  def update
    @part.update_attributes(params[:part])

    redirect_to :action => :index
  end

  def destroy
    @part.destroy

    redirect_to :action => :index
  end

  protected

  def find_part
    @part = Part.find(params[:id])
  end

end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :find_role, :only => [ :show, :edit, :update, :destroy]
  layout "admin"
  def index
    @roles = Role.page(params[:page]).per(5)
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(params[:role])
    @role.save
    redirect_to :action => :index
  end

  def edit
  end

  def show
  end

  def update
    @role.update_attributes(params[:role])

    redirect_to :action => :index
  end

  def destroy
    @role.destroy

    redirect_to :action => :index
  end

  protected

  def find_role
    @role = Role.find(params[:id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
  end
  def hot
    @tags = Tag.all.order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, :only => [ :show, :edit, :update, :destroy]
  layout "admin"
  def index
    @users = User.page(params[:page]).per(5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    redirect_to :action => :index
  end

  def edit
  end

  def show
  end

  def update
    @user.update_attributes(params[:user])

    redirect_to :action => :index
  end

  def destroy
    @user.destroy

    redirect_to :action => :index
  end

  protected

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/article_helper.rb
module ArticleHelper
  def part_options
    Part.all.map{|c| [c.name,c.id]}
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/parts/_form.html.erb
  <%= f.label :name," 栏目名称" %>
  <%= f.text_field :name %>
   
  <%= f.label :desc,"描述"%>
  <%= f.text_area :desc%>


  
  <%= f.label :state,"状态"%>
  
  <%= f.select :state,[['启用',1],['禁用',2]],:multiple=>"multiple" %>


  <%= f.submit "保存" %>

app/views/parts/edit.html.erb
<%= form_for @part, :url => { :controller => 'parts', :action => 'update',:id => @part} do |f| %>
  <%= render :partial => 'form',:locals =>{:f =>f} %> 
  <% end %>

app/views/parts/index.html.erb
<thead>
	<tr>
		<td><%= link_to '新增', {:controller => 'parts', :action => 'new'} %></td>
	</tr>
	<tr>
		<td>操作</td>

		<td>栏目名称</td><td>描述</td><td>状态</td>
	</tr>
</thead>
<tbody>
	<% @parts.each do |part|%>
	<tr>
		<td> <%= link_to '查看',part_path(part) %>
		<%= link_to '修改',edit_part_path(part) %>
		<%= link_to '删除',part_path(part),:method=>:delete,:confirm => "你确定要删除吗?"%> </td>
		<td><%= part.id%></td>
		<td><%= part.name%></td>
		<td><%= part.desc%></td>
		<td><%= part.state%></td>
	</tr>
	<% end%>
</tbody>

app/views/parts/new.html.erb
<%= form_for @part, :url => { :controller => 'parts', :action => 'create'} do |f| %>
<%= render :partial => 'form',:locals =>{:f =>f} %>
<% end %>

app/views/parts/show.html.erb
<%= @part.name %>
<%= @part.desc%>

app/views/roles/_form.html.erb
  <%= f.label :role_name," 角色名称" %>
  <%= f.text_field :role_name %>
   
  <%= f.label :role_desc,"角色描述"%>
  <%= f.text_area :role_desc%>


  
  <%= f.label :state,"角色状态"%>
  
  <%= f.select :state,[['启用',1],['禁用',2]],:multiple=>"multiple" %>


  <%= f.submit "保存" %>

app/views/roles/btn.html.erb
<%= content_for :breadcrumb do %>
<%= link_to '新增', {:controller => 'roles', :action => 'new'},{:class=>'btn'} %>
<%= link_to 'show',{:controller => 'roles', :action => 'show',:id => 1},{:class=>'btn'} %>
   
<% end %>

app/views/roles/edit.html.erb
<%= form_for @role, :url => { :controller => 'roles', :action => 'update',:id => @role } do |f| %>
  <%= render :partial => 'form',:locals =>{:f =>f} %> 
  <% end %>

app/views/roles/index.html.erb
<thead>
	<tr>
		<td><%= link_to '新增', {:controller => 'roles', :action => 'new'} %></td>
	</tr>
	<tr>
		<td>操作</td>

		<td>角色名称</td><td>角色描述</td><td>状态</td>
	</tr>
</thead>
<tbody>
	<% @roles.each do |role|%>
	<tr>
		<td> <%= link_to '查看',role_path(role) %>
		<%= link_to '修改',edit_role_path(role) %>
		<%= link_to '删除',role_path(role),:method=>:delete,:confirm => "你确定要删除吗?"%> </td>
		<td><%= role.id%></td>
		<td><%= role.role_name%></td>
		<td><%= role.role_desc%></td>
		<td><%= role.state%></td>
	</tr>
	<% end%>
</tbody>

app/views/roles/new.html.erb
<%= form_for @role, :url => { :controller => 'roles', :action => 'create'} do |f| %>
<%= render :partial => 'form',:locals =>{:f =>f} %>
<% end %>

app/views/roles/show.html.erb
<%= @role.role_name %>
<%= @role.role_desc%>

app/views/tags/index.html.erb
<% @tags.each  do |tag|%>
    <%= tag.name %>
<% end %>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :encrypted_password, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :encrypted_password, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_token, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :reset_password_token, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :reset_password_sent_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :remember_created_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :remember_created_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sign_in_count, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :sign_in_count, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :current_sign_in_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :last_sign_in_at, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_sign_in_ip, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :role_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :role_id, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:sign_in_count) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:role_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.sign_in_count %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.role_id %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sign_in_count) %>:</strong></dt>
  <dd><%= @user.sign_in_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:role_id) %>:</strong></dt>
  <dd><%= @user.role_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>